language: node_js
node_js:
  - "14.16.0"

before_script:
  - cd client
  - npm install
script:
  - npm test
    
deploy:
  skip_cleanup: true,
  provider: heroku
  app:
    master: tuk-tuk-tuk
    dtest: tuk-tuk-dtest
  api_key: $HEROKU_SECRET_KEY