sudo: false

language: node_js
node_js:
  - 9

branches:
  only:
    - master
    - dtest
    
deploy:
  provider: heroku
  app: tuk-tuk-tuk
  api_key:
    secure: b11112a1-4629-4dcd-9a4e-3671abb169b4