language: node_js
node_js:
  - "14.16.0"

jobs:
  include:
  - stage: deploy web
    before_script:
      - cd client
      - npm install
    script:
      - npm test
    deploy:
      edge: true
      provider: heroku
      app:
        master: tuk-tuk-tuk
        dtest: tuk-tuk-dtest
      api_key: $HEROKU_SECRET_KEY
  - stage: deploy api
    before_script:
      - cd server
      - npm install
    script:
      - npm test
    deploy:
      edge: true
      provider: heroku
      app:
        master: tuk-tuk-tuk-server
        dtest: tuk-tuk-dtest-server
      api_key: $HEROKU_SECRET_KEY