language: node_js
node_js:
  - "stable"

before_script:
  - cd client
  - npm install
script:
  - npm test
    
deploy:
  provider: heroku
  app:
    master: tuk-tuk-tuk
    dtest: tuk-tuk-dtest
  api_key: $HEROKU_SECRET_KEY