language: node_js
node_js:
  - "stable"

before_script:
  - cd client
  - npm install
script:
  - npm test
    
deploy:
  provider: heroku
  app:
    master: tuk-tuk-tuk
    dtest: tuk-tuk-dtest
  api_key:
    secure: b11112a1-4629-4dcd-9a4e-3671abb169b4